"""Mock recommendation engine for DiscoverAI.

The engine is intentionally data-driven and easy to replace with Spotify API,
vector search, or RAG later. For the MVP it ranks curated tracks against an
IntentProfile.
"""

from __future__ import annotations

from dataclasses import dataclass
from urllib.parse import quote_plus

from discover_ai_config import MAX_RECOMMENDATIONS
from discover_ai_intent import IntentProfile


@dataclass(frozen=True)
class Recommendation:
    """A single explainable music recommendation."""

    song_name: str
    artist: str
    language: str
    genres: tuple[str, ...]
    moods: tuple[str, ...]
    activities: tuple[str, ...]
    energy: str
    description: str
    why: str

    @property
    def spotify_search_url(self) -> str:
        """Return a Spotify Search URL with no authentication required."""
        return f"https://open.spotify.com/search/{quote_plus(self.song_name + ' ' + self.artist)}"


TRACK_LIBRARY: tuple[Recommendation, ...] = (
    # -----------------------------------------------------------------------
    # ENGLISH
    # -----------------------------------------------------------------------
    Recommendation(
        "A Walk",
        "Tycho",
        "English",
        ("Ambient", "Electronic", "Instrumental"),
        ("Focused", "Calm"),
        ("Coding", "Relax"),
        "Medium",
        "Warm instrumental electronic music with a steady pulse.",
        "It keeps a consistent tempo and avoids vocal clutter, making it useful for deep focus.",
    ),
    Recommendation(
        "Luv(sic) Pt3",
        "Nujabes feat. Shing02",
        "English",
        ("Lo-Fi", "Hip Hop", "Jazz"),
        ("Focused", "Warm"),
        ("Coding", "Coffee Break"),
        "Medium",
        "Jazz-influenced hip hop with a reflective rhythm.",
        "It balances familiarity and discovery with relaxed drums and melodic texture.",
    ),
    Recommendation(
        "Weightless",
        "Marconi Union",
        "English",
        ("Ambient", "Downtempo"),
        ("Calm", "Reflective"),
        ("Relax", "Rainy Evening"),
        "Low",
        "A slow ambient track designed around calm and space.",
        "It matches a low-energy intent and gives the listener room to decompress.",
    ),
    Recommendation(
        "Midnight City",
        "M83",
        "English",
        ("Alternative", "Electronic", "Pop"),
        ("Open", "Energized"),
        ("Road Trip", "Party"),
        "High",
        "Big synth-driven energy with a cinematic feeling.",
        "It fits an open-road mood while staying accessible and uplifting.",
    ),
    Recommendation(
        "Go!",
        "The Chemical Brothers",
        "English",
        ("Electronic", "Dance"),
        ("Driven", "Energized"),
        ("Workout", "Party"),
        "High",
        "Propulsive electronic production built for movement.",
        "It brings high energy and momentum without requiring much listener attention.",
    ),
    Recommendation(
        "Dang!",
        "Mac Miller feat. Anderson .Paak",
        "English",
        ("Hip Hop", "Soul", "Funk"),
        ("Social", "Warm"),
        ("Party", "Coffee Break"),
        "Medium",
        "A bright, groove-forward track with a social feel.",
        "It keeps the vibe upbeat while adding warmth and personality.",
    ),
    Recommendation(
        "Sweet Disposition",
        "The Temper Trap",
        "English",
        ("Indie", "Rock", "Alternative"),
        ("Open", "Hopeful"),
        ("Road Trip", "Open listening"),
        "High",
        "Expansive indie rock with a soaring chorus.",
        "It supports a travel-ready feeling and adds emotional lift.",
    ),
    Recommendation(
        "Holocene",
        "Bon Iver",
        "English",
        ("Indie", "Folk", "Acoustic"),
        ("Reflective", "Calm"),
        ("Rainy Evening", "Relax"),
        "Low",
        "Layered acoustic textures and intimate vocals.",
        "It matches a reflective mood while introducing a quieter discovery path.",
    ),
    Recommendation(
        "Tadow",
        "Masego and FKJ",
        "English",
        ("Jazz", "Soul", "R&B"),
        ("Warm", "Curious"),
        ("Coffee Break", "Relax"),
        "Medium",
        "Loose, polished jazz-soul with improvisational energy.",
        "It feels premium and relaxed while still giving the listener something fresh.",
    ),
    Recommendation(
        "Glue",
        "Bicep",
        "English",
        ("Electronic", "House", "Ambient"),
        ("Focused", "Open"),
        ("Coding", "Road Trip"),
        "Medium",
        "Atmospheric electronic music with a gradual build.",
        "It works for sustained concentration and gently expands beyond familiar sounds.",
    ),
    Recommendation(
        "Innerbloom",
        "RUFUS DU SOL",
        "English",
        ("Electronic", "Alternative", "Dance"),
        ("Open", "Reflective"),
        ("Road Trip", "Relax"),
        "Medium",
        "A long-form electronic track with emotional momentum.",
        "It blends discovery with immersion, ideal when the user wants a journey rather than a single hit.",
    ),
    Recommendation(
        "N95",
        "Kendrick Lamar",
        "English",
        ("Hip Hop", "Rap"),
        ("Driven", "Energized"),
        ("Workout", "Open listening"),
        "High",
        "Sharp, high-intensity hip hop with complex production.",
        "It adds energy and lyrical edge for users asking for momentum.",
    ),
    Recommendation(
        "Marea (We've Lost Dancing)",
        "Fred again..",
        "English",
        ("House", "Electronic"),
        ("Reflective", "Social"),
        ("Party", "Open listening"),
        "Medium",
        "Nostalgic and euphoric electronic house.",
        "It bridges the gap between deep reflection and a communal party atmosphere.",
    ),
    Recommendation(
        "One More Time",
        "Daft Punk",
        "English",
        ("Electronic", "Dance"),
        ("Energized", "Social"),
        ("Party", "Workout"),
        "High",
        "A timeless, upbeat dance anthem with heavily filtered vocals.",
        "It instantly injects energy into the room without feeling overly aggressive.",
    ),
    Recommendation(
        "White Gloves",
        "Khruangbin",
        "English",
        ("Alternative", "Soul", "Instrumental"),
        ("Calm", "Warm"),
        ("Relax", "Coffee Break"),
        "Low",
        "A quiet, bass-driven groove with minimal vocals.",
        "It acts as a soft sonic background that calms the environment down without disappearing entirely.",
    ),

    # -----------------------------------------------------------------------
    # HINDI
    # -----------------------------------------------------------------------
    Recommendation(
        "Ilahi",
        "Arijit Singh",
        "Hindi",
        ("Bollywood", "Pop"),
        ("Open", "Hopeful"),
        ("Road Trip", "Open listening"),
        "High",
        "A bright, acoustic-led travel anthem.",
        "It captures the expansive feeling of hitting the road with uplifting vocals.",
    ),
    Recommendation(
        "Kun Faya Kun",
        "A.R. Rahman",
        "Hindi",
        ("Sufi", "Bollywood", "Soul"),
        ("Reflective", "Calm"),
        ("Rainy Evening", "Relax"),
        "Low",
        "A deeply spiritual and atmospheric Sufi composition.",
        "It grounds the listener and provides a peaceful, introspective space.",
    ),
    Recommendation(
        "Udd Gaye",
        "Ritviz",
        "Hindi",
        ("Electronic", "Pop"),
        ("Energized", "Social"),
        ("Party", "Road Trip"),
        "High",
        "A quirky blend of Indian classical vocals and heavy electronic bass.",
        "It surprises the listener with a massive drop while keeping a deeply familiar vocal style.",
    ),
    Recommendation(
        "cold/mess",
        "Prateek Kuhad",
        "Hindi",
        ("Indie", "Folk", "Acoustic"),
        ("Reflective", "Warm"),
        ("Rainy Evening", "Coffee Break"),
        "Low",
        "Intimate acoustic folk with heartbreakingly honest songwriting.",
        "It matches quiet, rainy environments perfectly with minimal instrumentation.",
    ),
    Recommendation(
        "Choo Lo",
        "The Local Train",
        "Hindi",
        ("Rock", "Indie"),
        ("Reflective", "Hopeful"),
        ("Road Trip", "Open listening"),
        "Medium",
        "Nostalgic Indian indie rock with soaring guitar riffs.",
        "It hits the sweet spot for a reflective drive or a moment of late-night nostalgia.",
    ),
    Recommendation(
        "Kaam 25",
        "DIVINE",
        "Hindi",
        ("Rap", "Hip Hop"),
        ("Driven", "Focused"),
        ("Workout", "Coding"),
        "High",
        "Gritty, high-impact Mumbai street rap.",
        "It drives intense focus and relentless energy, perfect for pushing through a tough task.",
    ),
    Recommendation(
        "Namo Namo",
        "Amit Trivedi",
        "Hindi",
        ("Bollywood", "Folk"),
        ("Open", "Calm"),
        ("Road Trip", "Relax"),
        "Medium",
        "A soaring, folk-infused tribute with a steady, walking rhythm.",
        "It offers a sweeping, cinematic scale that feels deeply connected to travel and nature.",
    ),
    Recommendation(
        "Dil Chahta Hai",
        "Shankar-Ehsaan-Loy",
        "Hindi",
        ("Bollywood", "Pop"),
        ("Social", "Open"),
        ("Road Trip", "Party"),
        "High",
        "The quintessential Indian coming-of-age road trip song.",
        "It immediately lifts the mood and encourages communal singing.",
    ),
    Recommendation(
        "Iktara",
        "Kavita Seth",
        "Hindi",
        ("Acoustic", "Bollywood"),
        ("Warm", "Calm"),
        ("Coffee Break", "Relax"),
        "Low",
        "A gentle, guitar-plucked melody accented by soulful vocals.",
        "It brings warmth and a sense of stillness to a quiet afternoon break.",
    ),
    Recommendation(
        "Dus Bahane",
        "Vishal-Shekhar",
        "Hindi",
        ("Bollywood", "Dance"),
        ("Energized", "Driven"),
        ("Party", "Workout"),
        "High",
        "A glossy, high-tempo 2000s Bollywood dance classic.",
        "It offers immediate nostalgia wrapped in an undeniably high-energy beat.",
    ),
    Recommendation(
        "Nanchaku",
        "Seedhe Maut",
        "Hindi",
        ("Rap", "Hip Hop"),
        ("Driven", "Energized"),
        ("Workout", "Party"),
        "High",
        "Rapid-fire, technically complex rap over a blistering beat.",
        "It floods the listener with aggressive momentum for heavy lifting or intense exercise.",
    ),
    Recommendation(
        "Baarishein",
        "Anuv Jain",
        "Hindi",
        ("Indie", "Acoustic"),
        ("Reflective", "Warm"),
        ("Rainy Evening", "Relax"),
        "Low",
        "A raw, ukulele-driven ballad focusing on pure emotion.",
        "It leans completely into the aesthetic of rain and quiet vulnerability.",
    ),
    Recommendation(
        "Matargashti",
        "Mohit Chauhan",
        "Hindi",
        ("Bollywood", "Pop"),
        ("Curious", "Social"),
        ("Road Trip", "Coffee Break"),
        "Medium",
        "A playful, accordion-laced track full of whimsy.",
        "It breaks the ice and adds a lighthearted, bouncy energy to the room.",
    ),
    Recommendation(
        "Sunn Raha Hai",
        "Shreya Ghoshal",
        "Hindi",
        ("Bollywood", "Pop"),
        ("Reflective", "Open"),
        ("Open listening", "Rainy Evening"),
        "Medium",
        "A melodramatic, emotionally sweeping Bollywood ballad.",
        "It allows for deep emotional engagement when the listener wants to be fully immersed.",
    ),

    # -----------------------------------------------------------------------
    # TAMIL
    # -----------------------------------------------------------------------
    Recommendation(
        "New York Nagaram",
        "A.R. Rahman",
        "Tamil",
        ("Pop", "Tamil Pop", "Soul"),
        ("Reflective", "Calm"),
        ("Rainy Evening", "Relax"),
        "Low",
        "A smooth, jazz-tinged melody about urban solitude.",
        "It creates a beautiful sense of isolation, matching the vibe of a rainy evening perfectly.",
    ),
    Recommendation(
        "Vaathi Coming",
        "Anirudh Ravichander",
        "Tamil",
        ("Dance", "Tamil Pop", "Folk"),
        ("Energized", "Social"),
        ("Party", "Workout"),
        "High",
        "A massive, brass-heavy kuthu celebration.",
        "It demands physical movement and spikes the room's energy instantly.",
    ),
    Recommendation(
        "Vaseegara",
        "Harris Jayaraj",
        "Tamil",
        ("Pop", "Tamil Pop"),
        ("Warm", "Calm"),
        ("Relax", "Coffee Break"),
        "Low",
        "A lush, romantic melody with acoustic and synth layering.",
        "It is exceptionally smooth, offering a warm and familiar comfort to wind down.",
    ),
    Recommendation(
        "Thendral Vandhu",
        "Ilaiyaraaja",
        "Tamil",
        ("Folk", "Classic"),
        ("Calm", "Reflective"),
        ("Rainy Evening", "Relax"),
        "Low",
        "A masterclass in minimal, evocative orchestration by Ilaiyaraaja.",
        "It transports the listener to a calm, timeless space without any abrupt shifts in tone.",
    ),
    Recommendation(
        "Neruppu Da",
        "Santhosh Narayanan",
        "Tamil",
        ("Rock", "Rap", "Alternative"),
        ("Driven", "Energized"),
        ("Workout", "Road Trip"),
        "High",
        "An abrasive, heavily distorted rock anthem with rap elements.",
        "It taps into primal, cinematic adrenaline ideal for peaking during a workout.",
    ),
    Recommendation(
        "Munbe Vaa",
        "A.R. Rahman",
        "Tamil",
        ("Pop", "Tamil Pop"),
        ("Warm", "Hopeful"),
        ("Open listening", "Relax"),
        "Low",
        "An airy, ethereal composition with incredibly delicate vocals.",
        "It soothes the mind with sweeping melodies and complex, gentle instrumentation.",
    ),
    Recommendation(
        "Arabic Kuthu",
        "Anirudh Ravichander",
        "Tamil",
        ("Dance", "Pop"),
        ("Energized", "Social"),
        ("Party", "Workout"),
        "High",
        "A fusion of Middle Eastern rhythms and Tamil kuthu beats.",
        "It holds a relentless, infectious groove that anchors any upbeat environment.",
    ),
    Recommendation(
        "Loosu Penne",
        "Yuvan Shankar Raja",
        "Tamil",
        ("Alternative", "Pop"),
        ("Open", "Driven"),
        ("Road Trip", "Open listening"),
        "Medium",
        "A gritty, experimental pop track from the mid-2000s.",
        "It carries a specific nostalgic swagger that works beautifully for highway driving.",
    ),
    Recommendation(
        "Maruvaarthai",
        "Sid Sriram",
        "Tamil",
        ("Pop", "Tamil Pop"),
        ("Warm", "Curious"),
        ("Coffee Break", "Relax"),
        "Medium",
        "A vocal-heavy, passionately delivered modern classic.",
        "It engages the listener emotionally without overwhelming the acoustic space.",
    ),
    Recommendation(
        "Appadi Podu",
        "Vidyasagar",
        "Tamil",
        ("Dance", "Tamil Pop"),
        ("Energized", "Driven"),
        ("Party", "Workout"),
        "High",
        "A legendary fast-paced folk-dance crossover.",
        "It is pure, unfiltered momentum designed to raise the heart rate.",
    ),
    Recommendation(
        "Club le Mabbu le",
        "Hiphop Tamizha",
        "Tamil",
        ("Rap", "Hip Hop"),
        ("Driven", "Social"),
        ("Party", "Road Trip"),
        "High",
        "The track that essentially birthed modern Tamil hip hop.",
        "It delivers a punchy, rhythmic bounce perfect for a hype playlist.",
    ),
    Recommendation(
        "Urvasi Urvasi",
        "A.R. Rahman",
        "Tamil",
        ("Pop", "Dance"),
        ("Social", "Open"),
        ("Party", "Road Trip"),
        "High",
        "A genre-defying 90s masterpiece with unmatched swagger.",
        "It bridges generations at a party while maintaining an incredibly cool groove.",
    ),

    # -----------------------------------------------------------------------
    # TELUGU
    # -----------------------------------------------------------------------
    Recommendation(
        "Oo Antava",
        "Devi Sri Prasad",
        "Telugu",
        ("Dance", "Tollywood"),
        ("Energized", "Driven"),
        ("Party", "Workout"),
        "High",
        "A bass-heavy, hypnotic dance track with a dark undertone.",
        "It provides a relentless, pulsing beat that dominates the room's energy.",
    ),
    Recommendation(
        "Butta Bomma",
        "Thaman S",
        "Telugu",
        ("Pop", "Tollywood"),
        ("Warm", "Social"),
        ("Road Trip", "Party"),
        "Medium",
        "A breezy, impossibly catchy pop song.",
        "It keeps the mood extremely light and accessible for mixed crowds.",
    ),
    Recommendation(
        "Dosti",
        "M.M. Keeravani",
        "Telugu",
        ("Rock", "Tollywood"),
        ("Driven", "Hopeful"),
        ("Workout", "Road Trip"),
        "High",
        "A massive, orchestral rock anthem built on themes of brotherhood.",
        "It offers cinematic motivation when the user asks for driven energy.",
    ),
    Recommendation(
        "Ramuloo Ramulaa",
        "Thaman S",
        "Telugu",
        ("Dance", "Tollywood"),
        ("Energized", "Social"),
        ("Party", "Road Trip"),
        "High",
        "A high-voltage folk-pop blend with a massive synth presence.",
        "It commands attention and functions as a peak-time party starter.",
    ),
    Recommendation(
        "Inkem Inkem Inkem Kaavaale",
        "Gopi Sundar",
        "Telugu",
        ("Pop", "Melody"),
        ("Warm", "Calm"),
        ("Relax", "Coffee Break"),
        "Low",
        "A soft, classical-adjacent melody backed by lush acoustic guitars.",
        "It sits perfectly in the background, offering warmth without distraction.",
    ),
    Recommendation(
        "Seethamma Vakitlo",
        "Mickey J. Meyer",
        "Telugu",
        ("Pop", "Tollywood"),
        ("Calm", "Reflective"),
        ("Rainy Evening", "Relax"),
        "Low",
        "A highly traditional, soothing melody with a modern orchestral polish.",
        "It wraps the listener in comfort and works well for quiet introspection.",
    ),
    Recommendation(
        "Cheppave Chirugali",
        "Mani Sharma",
        "Telugu",
        ("Melody", "Classic"),
        ("Reflective", "Warm"),
        ("Rainy Evening", "Coffee Break"),
        "Low",
        "A breezy 2000s classic known for its flute and string sections.",
        "It acts as a gentle nostalgic anchor for a lazy afternoon.",
    ),
    Recommendation(
        "Ye Chilipi",
        "A.R. Rahman",
        "Telugu",
        ("Pop", "Tollywood"),
        ("Open", "Hopeful"),
        ("Road Trip", "Open listening"),
        "Medium",
        "A bright, rhythmically complex track with uplifting vocals.",
        "It mirrors the momentum of a road trip while keeping the energy breezy.",
    ),
    Recommendation(
        "Srivalli",
        "Sid Sriram",
        "Telugu",
        ("Pop", "Tollywood"),
        ("Warm", "Curious"),
        ("Open listening", "Relax"),
        "Medium",
        "A slightly off-kilter, folk-inspired melody that builds over time.",
        "It balances familiar pop structures with unique instrumental choices.",
    ),
    Recommendation(
        "Ringa Ringa",
        "Devi Sri Prasad",
        "Telugu",
        ("Dance", "Tollywood"),
        ("Energized", "Social"),
        ("Party", "Workout"),
        "High",
        "An aggressively fast, rhythm-focused dance staple.",
        "It leaves zero room for boredom and forces the listener to match its pace.",
    ),
    Recommendation(
        "Aagi Aagi",
        "Vivek Sagar",
        "Telugu",
        ("Indie", "Jazz"),
        ("Calm", "Curious"),
        ("Coffee Break", "Relax"),
        "Low",
        "A lo-fi and jazz-infused Telugu indie gem.",
        "It provides a highly sophisticated, relaxing backdrop for focus or a coffee break.",
    ),
    Recommendation(
        "Samajavaragamana",
        "Thaman S",
        "Telugu",
        ("Pop", "Tollywood"),
        ("Open", "Warm"),
        ("Road Trip", "Coffee Break"),
        "Medium",
        "A melodic pop song anchored heavily by electric keyboards and tight programming.",
        "It feels grand but moves at a comfortable, walking tempo.",
    ),

    # -----------------------------------------------------------------------
    # KOREAN
    # -----------------------------------------------------------------------
    Recommendation(
        "Dynamite",
        "BTS",
        "Korean",
        ("Pop", "K-Pop", "Dance"),
        ("Energized", "Social"),
        ("Party", "Workout"),
        "High",
        "A relentlessly upbeat disco-pop explosion.",
        "It guarantees an instant mood lift and universal appeal for a party setting.",
    ),
    Recommendation(
        "How You Like That",
        "BLACKPINK",
        "Korean",
        ("Electronic", "K-Pop", "Hip Hop"),
        ("Driven", "Energized"),
        ("Workout", "Party"),
        "High",
        "A bold, brass-heavy track with a massive beat drop.",
        "It serves as perfect fuel for heavy lifting or high-intensity intervals.",
    ),
    Recommendation(
        "Palette",
        "IU",
        "Korean",
        ("R&B", "K-Pop"),
        ("Warm", "Calm"),
        ("Coffee Break", "Relax"),
        "Low",
        "A smooth, understated R&B track about coming of age.",
        "It offers a highly polished, aesthetic calm ideal for winding down.",
    ),
    Recommendation(
        "Ditto",
        "NewJeans",
        "Korean",
        ("Lo-Fi", "K-Pop", "Dance"),
        ("Reflective", "Calm"),
        ("Rainy Evening", "Relax"),
        "Medium",
        "A nostalgic, breakbeat-driven pop track with a muffled warmth.",
        "It captures a deeply cozy, slightly melancholic vibe suitable for a rainy day.",
    ),
    Recommendation(
        "seoul",
        "RM",
        "Korean",
        ("Hip Hop", "Lo-Fi"),
        ("Reflective", "Focused"),
        ("Coding", "Rainy Evening"),
        "Low",
        "A laid-back, atmospheric rap track produced by Honne.",
        "It gives the listener an unobtrusive but beautifully textured background for focus.",
    ),
    Recommendation(
        "God's Menu",
        "Stray Kids",
        "Korean",
        ("Rap", "K-Pop", "Electronic"),
        ("Driven", "Energized"),
        ("Workout", "Coding"),
        "High",
        "An aggressive, chaotic, and heavily synthesized hype track.",
        "It completely shatters low energy and commands total attention.",
    ),
    Recommendation(
        "Any Song",
        "Zico",
        "Korean",
        ("Hip Hop", "Pop"),
        ("Social", "Curious"),
        ("Party", "Coffee Break"),
        "Medium",
        "A piano-led, incredibly bouncy hip-hop crossover.",
        "It feels deeply casual and fun, perfect for breaking up a monotonous afternoon.",
    ),
    Recommendation(
        "instagram",
        "DEAN",
        "Korean",
        ("R&B", "Soul"),
        ("Reflective", "Calm"),
        ("Rainy Evening", "Relax"),
        "Low",
        "A minimalist, guitar-based R&B track about late-night scrolling.",
        "It matches the emotional frequency of being alone at night with one's thoughts.",
    ),
    Recommendation(
        "Psycho",
        "Red Velvet",
        "Korean",
        ("R&B", "K-Pop"),
        ("Open", "Reflective"),
        ("Open listening", "Road Trip"),
        "Medium",
        "An elegant, string-laden pop song with complex vocal harmonies.",
        "It strikes a beautiful balance between eerie atmosphere and catchy melodies.",
    ),
    Recommendation(
        "BANG BANG BANG",
        "BIGBANG",
        "Korean",
        ("Dance", "K-Pop", "Electronic"),
        ("Energized", "Driven"),
        ("Party", "Workout"),
        "High",
        "An arena-ready electronic dance anthem from the titans of K-Pop.",
        "It is pure, unadulterated hype meant for maximum volume.",
    ),
    Recommendation(
        "VERY NICE",
        "SEVENTEEN",
        "Korean",
        ("Pop", "K-Pop"),
        ("Hopeful", "Energized"),
        ("Road Trip", "Party"),
        "High",
        "A funk-driven, exceptionally tight pop song featuring live brass.",
        "It carries a frantic, joyous energy that makes sitting still impossible.",
    ),
    Recommendation(
        "Square (2017)",
        "Yerin Baek",
        "Korean",
        ("K-Indie", "Pop"),
        ("Warm", "Open"),
        ("Coffee Break", "Road Trip"),
        "Medium",
        "A breezy, indie-pop track with English lyrics and gorgeous vocals.",
        "It feels like sunshine through a window, bringing a warm glow to any activity.",
    ),

    # -----------------------------------------------------------------------
    # JAPANESE
    # -----------------------------------------------------------------------
    Recommendation(
        "Yoru ni Kakeru",
        "YOASOBI",
        "Japanese",
        ("J-Pop", "Electronic"),
        ("Driven", "Energized"),
        ("Road Trip", "Workout"),
        "High",
        "A hyper-melodic, piano-driven pop song with a racing tempo.",
        "It offers blinding speed and energy, contrasting with its darker lyrical themes.",
    ),
    Recommendation(
        "Lemon",
        "Kenshi Yonezu",
        "Japanese",
        ("J-Pop", "Alternative"),
        ("Reflective", "Open"),
        ("Open listening", "Rainy Evening"),
        "Medium",
        "A slightly off-beat, emotionally devastating pop-rock masterpiece.",
        "It asks for the listener's attention and rewards it with a deep emotional payoff.",
    ),
    Recommendation(
        "Aruarian Dance",
        "Nujabes",
        "Japanese",
        ("Lo-Fi", "Jazz", "Instrumental"),
        ("Focused", "Calm"),
        ("Coding", "Relax"),
        "Low",
        "The track that largely defined the modern chillhop/lo-fi movement.",
        "It provides a hypnotic, looping acoustic guitar perfect for disappearing into work.",
    ),
    Recommendation(
        "First Love",
        "Hikaru Utada",
        "Japanese",
        ("Pop", "Ballad"),
        ("Reflective", "Calm"),
        ("Rainy Evening", "Relax"),
        "Low",
        "A deeply nostalgic and universally recognized 90s J-Pop ballad.",
        "It is engineered for looking out a rainy window and feeling introspective.",
    ),
    Recommendation(
        "Gurenge",
        "LiSA",
        "Japanese",
        ("Rock", "J-Pop"),
        ("Driven", "Energized"),
        ("Workout", "Road Trip"),
        "High",
        "A roaring, guitar-heavy anime opening designed for battle.",
        "It pushes adrenaline to the absolute limit for the hardest part of a workout.",
    ),
    Recommendation(
        "Zenzenzense",
        "RADWIMPS",
        "Japanese",
        ("Rock", "Alternative"),
        ("Hopeful", "Open"),
        ("Road Trip", "Open listening"),
        "High",
        "A fast-paced, math-rock influenced track with massive emotional scale.",
        "It embodies the feeling of moving forward rapidly, making it an elite driving song.",
    ),
    Recommendation(
        "Shinunoga E-Wa",
        "Fujii Kaze",
        "Japanese",
        ("R&B", "J-Pop"),
        ("Warm", "Curious"),
        ("Coffee Break", "Relax"),
        "Medium",
        "A sultry, piano-laced R&B track with traditional Japanese melodic scales.",
        "It offers a sophisticated, slightly moody atmosphere for a low-key gathering.",
    ),
    Recommendation(
        "Usseewa",
        "Ado",
        "Japanese",
        ("Rock", "Pop"),
        ("Driven", "Energized"),
        ("Workout", "Coding"),
        "High",
        "A furious, theatrical vocal performance criticizing societal norms.",
        "It acts as a chaotic, aggressive reset button when you need to power through frustration.",
    ),
    Recommendation(
        "Magic Ways",
        "Tatsuro Yamashita",
        "Japanese",
        ("City Pop", "Soul"),
        ("Warm", "Calm"),
        ("Coffee Break", "Road Trip"),
        "Medium",
        "A slick, bass-slapping 80s City Pop groove.",
        "It bathes the room in neon-lit nostalgia, keeping things upbeat but totally relaxed.",
    ),
    Recommendation(
        "Kaikai Kitan",
        "Eve",
        "Japanese",
        ("Rock", "J-Pop"),
        ("Driven", "Open"),
        ("Workout", "Road Trip"),
        "High",
        "A complex, dense rock track with rapid vocal delivery.",
        "It supplies consistent, driving momentum that works beautifully on a highway.",
    ),
    Recommendation(
        "Kaiju no Hanauta",
        "Vaundy",
        "Japanese",
        ("J-Pop", "Rock"),
        ("Hopeful", "Energized"),
        ("Road Trip", "Open listening"),
        "High",
        "An anthemic, stadium-ready rock song that builds into a massive chorus.",
        "It encourages singing along and lifts the mood of everyone in the car.",
    ),
    Recommendation(
        "Stay With Me",
        "Miki Matsubara",
        "Japanese",
        ("City Pop", "Pop"),
        ("Social", "Warm"),
        ("Party", "Relax"),
        "Medium",
        "The quintessential City Pop anthem filled with brass and strings.",
        "It bridges a laid-back lounge aesthetic with just enough groove to dance to.",
    ),

    # -----------------------------------------------------------------------
    # SPANISH
    # -----------------------------------------------------------------------
    Recommendation(
        "Tití Me Preguntó",
        "Bad Bunny",
        "Spanish",
        ("Reggaeton", "Trap"),
        ("Energized", "Social"),
        ("Party", "Workout"),
        "High",
        "A chaotic, multi-part reggaeton track that shifts tempos unpredictably.",
        "It commands the dancefloor and forces the crowd to move.",
    ),
    Recommendation(
        "DESPECHÁ",
        "Rosalía",
        "Spanish",
        ("Pop", "Dance", "Alternative"),
        ("Energized", "Open"),
        ("Party", "Road Trip"),
        "High",
        "A breezy, mambo-influenced pop song made for the summer.",
        "It acts as a burst of vitamin D, instantly brightening the mood.",
    ),
    Recommendation(
        "Mi Gente",
        "J Balvin, Willy William",
        "Spanish",
        ("Reggaeton", "Dance"),
        ("Driven", "Social"),
        ("Workout", "Party"),
        "High",
        "A global dance hit built around a squawking, unavoidable vocal sample.",
        "It relies on an infectious, repetitive groove that drives high-intensity movement.",
    ),
    Recommendation(
        "Bzrp Music Sessions, Vol. 52",
        "Bizarrap, Quevedo",
        "Spanish",
        ("Electronic", "Rap", "Pop"),
        ("Energized", "Driven"),
        ("Party", "Workout"),
        "High",
        "A four-on-the-floor club anthem with a legendary beat drop.",
        "It is designed to make crowds jump, pushing energy to the absolute maximum.",
    ),
    Recommendation(
        "Ahora Te Puedes Marchar",
        "Luis Miguel",
        "Spanish",
        ("Pop", "Dance"),
        ("Hopeful", "Social"),
        ("Road Trip", "Party"),
        "High",
        "A flawless 80s synth-pop cover full of joy and defiance.",
        "It is impossible not to sing along to, acting as a perfect throwback for mixed company.",
    ),
    Recommendation(
        "Hasta la Raíz",
        "Natalia Lafourcade",
        "Spanish",
        ("Folk", "Alternative"),
        ("Reflective", "Warm"),
        ("Coffee Break", "Relax"),
        "Medium",
        "A beautiful, acoustic guitar-driven declaration of identity.",
        "It feels grounded and organic, ideal for starting the morning or a quiet afternoon.",
    ),
    Recommendation(
        "Tú Me Dejaste De Querer",
        "C. Tangana",
        "Spanish",
        ("Pop", "Alternative"),
        ("Reflective", "Curious"),
        ("Open listening", "Relax"),
        "Medium",
        "A genre-blending mix of flamenco, bachata, and modern pop.",
        "It offers rich musical textures while maintaining a totally relaxed tempo.",
    ),
    Recommendation(
        "La Tortura",
        "Shakira, Alejandro Sanz",
        "Spanish",
        ("Pop", "Reggaeton"),
        ("Driven", "Social"),
        ("Party", "Road Trip"),
        "High",
        "A classic reggaeton-pop crossover with incredible vocal chemistry.",
        "It brings an older, familiar swagger that still works perfectly in a party setting.",
    ),
    Recommendation(
        "Latinoamérica",
        "Calle 13",
        "Spanish",
        ("Alternative", "Rap", "Folk"),
        ("Open", "Reflective"),
        ("Open listening", "Road Trip"),
        "Medium",
        "A sweeping, cinematic ode to a continent featuring organic instrumentation.",
        "It provides a deep, immersive listening experience that demands your attention.",
    ),
    Recommendation(
        "PROVENZA",
        "Karol G",
        "Spanish",
        ("Pop", "Reggaeton"),
        ("Warm", "Calm"),
        ("Relax", "Road Trip"),
        "Medium",
        "A soft, afrobeats-influenced reggaeton track with a gentle bounce.",
        "It keeps a rhythmic groove alive while allowing the listener to fully decompress.",
    ),
    Recommendation(
        "El Rey",
        "Vicente Fernández",
        "Spanish",
        ("Mariachi", "Folk"),
        ("Social", "Open"),
        ("Party", "Open listening"),
        "High",
        "The ultimate Mexican mariachi standard meant to be belted out.",
        "It is a communal, dramatic experience that acts as the climax of any social gathering.",
    ),
    Recommendation(
        "Chan Chan",
        "Buena Vista Social Club",
        "Spanish",
        ("Folk", "Acoustic"),
        ("Warm", "Calm"),
        ("Coffee Break", "Relax"),
        "Low",
        "A legendary slice of traditional Cuban Son.",
        "It oozes atmosphere and class, immediately turning any room into a smoky Havana lounge.",
    ),
)


class RecommendationEngine:
    """Rank curated recommendations against the user's current intent."""

    def recommend(self, profile: IntentProfile) -> list[Recommendation]:
        """Return the strongest recommendations for an intent profile."""
        
        # Safely extract language, defaulting to "Auto" if it isn't set
        target_lang = getattr(profile, "language", "Auto")

        # Filter the candidate pool based on language selection
        if target_lang == "Auto":
            candidates = TRACK_LIBRARY
        else:
            candidates = tuple(
                track for track in TRACK_LIBRARY if track.language == target_lang
            )

        # Apply existing scoring logic to the filtered candidates
        ranked = sorted(
            candidates,
            key=lambda item: self._score(item, profile),
            reverse=True,
        )
        return ranked[:MAX_RECOMMENDATIONS]

    def _score(self, item: Recommendation, profile: IntentProfile) -> int:
        """Score one recommendation against intent dimensions."""
        score = 0
        if profile.activity in item.activities:
            score += 4
        if profile.mood in item.moods:
            score += 3
        if profile.energy == item.energy:
            score += 3
        score += len(set(profile.preferred_genres).intersection(set(item.genres))) * 2
        
        # Safe access to discovery_level in case it isn't always present
        discovery_level = getattr(profile, "discovery_level", "Familiar")
        if discovery_level == "Exploratory":
            score += len(item.genres)
        if discovery_level == "Familiar" and profile.energy == item.energy:
            score += 1
            
        return score